### ISSUE TITLE
AlexNet/CreateTFRecord.py 中 def writerRecord(save_path, HOME_PATH, coord=None, t_id=0):

### ISSUE THREAD

**Issue by miss-peret** [wmpscc/CNN-Series-Getting-Started-and-PyTorch-Implementation#1]
def writerRecord(save_path, HOME_PATH, coord=None, t_id=0):
    writerTrain = tf.python_io.TFRecordWriter(os.path.join(save_path, "train" + str(t_id) + ".tfrecords"))
    randIndexTrain = random.sample(range(0, len(trainPaths)), len(trainPaths))
    size = int(len(randIndexTrain) / 4)
    randIndexTrain = randIndexTrain[t_id * size: (t_id + 1) * size]
    sess = tf.Session()

使用一个t_id变量来将训练集分为几个不同的tfrecords吗？
但是使用random.sample()，每次运行都会重新随机，用[t_id * size: (t_id + 1) * size]来确定范围，无法保证每次随机结果一样，那么每次手动更改t_id变量将无意义，无法生成所有图像的tfrecords
建议一次随机后使t_id自动循环，避免多次随机
本人新手，不太理解，所以提问一下，还请指教^_^

**Comment by wmpscc** [comment]
已修改
